dist: bionic
language: php

env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: SETUP=lowest
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4
    - php: 7.4
      env: SETUP=lowest

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - printf "\n" | pecl install -f memcached redis
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE forge;'

install:
  - if [[ $SETUP='stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP='lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - cp .env.example .env
  - php artisan key:generate
  - echo " ============================================================ ";echo ">>> checking code formats start...";
  - vendor/bin/phpcs --standard=PSR2 -q app/
  - echo ">>> checking code formats finished.";echo " ============================================================ ";echo
  - echo " ============================================================ ";echo ">>> static debugging start...";
  - vendor/bin/phpstan analyse -l 0 -c phpstan.neon app/
  - echo ">>> static debugging finished.";echo " ============================================================ ";echo
  - echo " ============================================================ ";echo ">>> php unit-test start...";
  - vendor/bin/phpunit tests/
  - echo ">>> php unit-test finished.";echo " ============================================================ ";echo
